name: Generate Language Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar estatísticas de linguagens
        uses: githubocto/flat@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          template: |
            {
              "languages": [
                {% for language in github.event.repositories[0].languages %}
                  {
                    "name": "{{ language.name }}",
                    "size": {{ language.size }},
                    "color": "{{ language.color }}"
                  }{% if not loop.last %},{% endif %}
                {% endfor %}
              ]
            }
          output_file: language-stats.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install chartjs-node-canvas

      - name: Gerar gráfico
        run: node scripts/generate-chart.js

      - name: Commit e push do gráfico
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add language-chart.png
          git commit -m "Atualiza gráfico" || exit 0
          git push
